var icons = {
  about : '\uE873',
  addGroup : '\uE2CC',
  addPhoto : '\uE439',
  alerts : '\uE7F4',
  alarm : '\uE855',
  arrowBack : '\uE5C4',
  assignment : '\uE85D',
  check : '\uE5CA',
  checkCircle : '\uE86C',
  close : '\uE5CD',
  cMenu : '\uE5D4',
  config : '\uE8B8',
  email : '\uE0BE',
  erase : '\uE92B',
  error : '\uE000',
  errorOutline : '\uE001',
  group : '\uE2C7',
  keyboardArrowLeft : '\uE314',
  keyboardArrowRight : '\uE315',
  keyboardArrowDown : '\uE313',
  keyboardArrowUp : '\uE316',
  lList : '\uE8EF',
  lModule : '\uE8F0',
  lock : '\uE897',
  logout : '\uE8AC',
  menu : '\uE5D2',
  news : '\uE645',
  noteAdd : '\uE89C',
  star : '\uE838',
  starBorder : '\uE83A',
  uCircle : '\uE853',
  user : '\uE7FD',
  users : '\uE7EF',
  warning : '\uE002'
};

module.exports = {
  icons : icons
}